### ISSUE TITLE
React Native module feedback

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/flic2lib-ios#11]
Hi,

We have been working on a React Native module for internal usage. However we are making it publicly available for everybody to use.

**(edit: forgot to include the repo)**
Link to repository: https://github.com/X-Guard/react-native-flic2

It would be wonderful if the Flic devs could take a look at our current source code and implementation and maybe provide us with feedback on some obvious implementation mistakes we might have made.

At this point barely anybody is using the module, so we can easily make any API changes as well.

We are still facing some issues with:
- Changing the name (this does not really seem to work for us, but we are still checking why, see issue #10)
- armv7 support (waiting for support as discussed in issue #7)
- not having the .framework included in our source code but dynamically linked from your repository (#1)
- differences between how isReady is handled on Android and iOS (#9)

They are all very minor, and we are happy with the current implementation. An example app is available at https://github.com/X-Guard/react-native-flic2-example.

![IMG_4902](https://user-images.githubusercontent.com/14085897/72416233-7cf01980-3776-11ea-87d7-ad2941497bac.PNG)

**Comment by AntonMeier** [comment]
This looks really cool! We are taking a look at it and have some feedback. @Emill will comment on some code related feedback soon, but I just wanted to make some quick comments:

* Try if writing the nickname works better in the latest beta.
* armv7 should be fixed with in the latest beta.
* I don't recommend translating the battery voltage to a percentage since it will not be accurate. Perhaps instead just show battery "Ok"/"Not Ok" with a cutoff around 2.65 V.
* Since people are likely to use this react wrapper as a starting point in the future it would probably be good if the scanning flow somehow included the state events in the UI. I am referring to FLICButtonScannerStatusEvent. But this is up to you.
* The trigger modes are handled differently by your code on Android / iOS, which is understandable since the platforms work differently, but since you have a wrapper I suggest you make the behavior the seemingly the same. So, for example, setting `FLICButtonTriggerModeClick` on iOS would be the same as listening to the `public void onButtonClickOrHold(Flic2Button button, boolean wasQueued, boolean lastQueued, long timestamp, boolean isClick, boolean isHold)` callback on Android.
So I would recommend that in your method `buttonSetMode(uuid, mode)` when you set the mode you should store a state parameter for android and then on click events you check this mode in each of the `onButtonClickOrHold()`, `onButtonSingleOrDoubleClick ()` and `onButtonSingleOrDoubleClickOrHold ()`. Do you understand what I mean?

I think that it what I had for now, but I will take a closer look and actually try it out later.

Thank you!

**Comment by jdegger** [comment]
Thanks for the feedback!

>     * Try if writing the nickname works better in the latest beta.
Will do! This was still on our todo list.
 
>     * armv7 should be fixed with in the latest beta.
Testing has started, @wesdewitte will report results as I'm out of office tomorrow :)

>     * I don't recommend translating the battery voltage to a percentage since it will not be accurate. Perhaps instead just show battery "Ok"/"Not Ok" with a cutoff around 2.65 V.
We were struggling with this as well, especially since we see a lot of fluctuation between the calculated battery percentage every call we make. We will change the behavior. 

>     * Since people are likely to use this react wrapper as a starting point in the future it would probably be good if the scanning flow somehow included the state events in the UI. I am referring to FLICButtonScannerStatusEvent. But this is up to you.
We discussed this, we will try and emit the data. It was not immediately needed for our own use case but, like you said, since people are going to use it, it's up to them to decide whatever they need. We will emit the status event as well. Good idea!

>     * The trigger modes are handled differently by your code on Android / iOS, which is understandable since the platforms work differently, but since you have a wrapper I suggest you make the behavior the seemingly the same. So, for example, setting `FLICButtonTriggerModeClickAndHold` on iOS would be the same as listening to the `public void onButtonClickOrHold(Flic2Button button, boolean wasQueued, boolean lastQueued, long timestamp, boolean isClick, boolean isHold)` callback on Android.
>       So I would recommend that in your method `buttonSetMode(uuid, mode)` when you set the mode you should store a state parameter for android and then on click events you check this mode in each of the `onButtonClickOrHold()`, `onButtonSingleOrDoubleClick ()` and `onButtonSingleOrDoubleClickOrHold ()`. Do you understand what I mean?
Yes, I think we discussed this idea at some point, but we didn't actually build it. We will add this to our todo list as well.

Thanks so far!

**Comment by Emill** [comment]
Nice work! Some comments:

1. `sanResult` in Readme, should be `scanResult`.
2. On Android `timestamp` is not `age`. To get `age` in seconds, use `wasQueued ? 0 : (button.getReadyTimestamp() - timestamp) / 1000`. And you should use an int or a double to store the age, not a string.
3. Please call `button.getLastKnownBatteryLevel()` once and store the result, instead of calling it three times.
4. The JS button object should be updated when the `onBatteryLevelUpdated` callback is received. Also emit that event to the user in JS?
5. From an API design I don't think it's good that the user should call `this.getButtons();` all the times, as done in the documentation. Can't the library internals update itself when needed instead?
6. Please implement? and document events such as `didReceiveNewName`, `buttonConnectionReady` etc.
7. Remove `buttonConnectionStarted`.
8. Expose `setAutoDisconnectTime`?
9. The `getName` and `setName`, do they get/set the same name and do they behave the same on Android/iOS? The fact that both the terminology "internal button name" and "nickname" are used here confuses me.
10. Add `button.getSerialNumber()`?
11. `get the estimated battery level` -> `get the estimated battery level in percentage between 0 and 100`.

I'm also wondering a bit about the threading in Android/React. I see you call `Looper.prepare();` but then you use `new Handler(Looper.getMainLooper())` later, indicating the prepared looper isn't used. Would it be possible to run the Android Flic2 lib on the same thread as the React javascript, or at least the same thread as all the methods annotated by `@ReactMethod` run on? That would be preferable to avoid race conditions and stuff. If Android Handlers can't be used, I think you should be able to use the `HandlerInterface` class instead. I see your class implements `HandlerInterface` (currently the methods are recursive?) Use `Flic2Manager.init(Context, HandlerInterface, LoggerInterface)` to specify the handler interface.

**Comment by jdegger** [comment]
We have reworked a lot on the last couple of updates of the library 👍 https://github.com/X-Guard/react-native-flic2

Thanks again for the feedback, this was a big help. I'm closing this issue now but of course your feedback is still welcome.
