### ISSUE TITLE
Issue with Xcode 11.4: No longer able to run on simulator

### ISSUE THREAD

**Issue by jusefjames** [50ButtonsEach/flic2lib-ios#15]
Hi, when using Xcode 11.4 I get this error message when building for iOS Simulator:
`"Building for iOS Simulator, but the linked and embedded framework 'fliclib.framework' was built for iOS."`
same for flic2lib.framework.
Is there any workaround?
Running on real devices without issues...

Thanks

**Comment by AntonMeier** [comment]
Yes, you are correct. This is new with 11.4. We are discussing it for Flic 1 here as well: [https://github.com/50ButtonsEach/fliclib-ios/issues/39](https://github.com/50ButtonsEach/fliclib-ios/issues/39).

I'll see what I can come up with.

**Comment by yosoycody** [comment]
Same issue. This is preventing me from building my project with the simulator...

**Comment by AntonMeier** [comment]
After some consideration I'm now leaning towards moving over to Apple's new XCFramework packaging format. The main purpose of XCFrameworks is to solve the multi-architecture issues of a regular framework. An added bonus of this would be that it would be easy for us to add additional platforms (such as macOS) to the same package in the future.

However, I do believe Xcode 11 is a requirement in order to use XCFrameworks, which may be a deal breaker for some. 

I really don't like the idea of requiring custom build scripts to use the flic2lib.framework, which would be the only other option. 

Let me know if you have any thoughts.

**Comment by AntonMeier** [comment]
I have made a beta version of flic2lib as a XCFramework bundle that can be downloaded here: [flic2lib.1.0.6.Beta1.xcframework.zip](https://misc-scl-cdn.s3.amazonaws.com/flic2lib.1.0.6.Beta1.xcframework.zip)

It would be nice if someone tried it out so that I can get some more feedback.

Basically this bundle includes builds for both `iphoneos` and `iphonesimulator`. I am aware that this is not backwards compatible with Xcode 10.

Instructions:

1. Drag and drop the whole `flic2lib.xcframework` folder to `Frameworks, Libraries and Embedded Content` section under the General tab of your application target settings. Ensure the `flic2lib.xcframework` is listed as `Embed & Sign` and, if prompted, check `Copy items if needed`. Doing this should automatically add the xcframework to `Link Binary With Libraries` under the Build Phases tab.

2. In your source code, replace `#import <flic2lib/flic2lib.h>` with either `@ import flic2lib;` (Objective-C) or `@import flic2lib` (Swift).

You should now be able to switch between device and simulator without issues.

**Comment by jusefjames** [comment]
Hi, thanks for this quick XCFramework Beta. In the meantime i switched to build script method mentioned here from Jonazon: https://github.com/50ButtonsEach/fliclib-ios/issues/39
Had to modify the script for using flic2lib also but this method worked for me. Build and Run for Devices and Simulator was fine.

Now I removed the flic2lib stuff from the build script and followed your instructions using the XCFramework Beta.
Also runs fine on my app and in simulator.

Would it also be possible to make a XCFramework for fliclib? This would be perfect and we would not need the build script any more.
Thanks again for your help...

**Comment by AntonMeier** [comment]
I just made an official release `1.1.0` that uses XCFramework bundles. Regarding the fliclib for Flic 1, we will hopefully update that later this week as well.
