### ISSUE TITLE
Use Flicbutton across more than one view Controller

### ISSUE THREAD

**Issue by jcarles** [50ButtonsEach/flic2lib-ios#29]
How can I use the flicbuttondelegate protocol across more than one viewcontroller. When I set it on the first viewcontroller, methods are linked to this , and when I change to another view controller It reacts to methods on the first viewcontroller.
Can I change the buttonDelegate when I load a new ViewController? 
Thanks

**Comment by oskob** [comment]
Hi!

There are a few ways to do this and since there is no single best way to do this, it's a bit outside the scope of the library itself. 

One popular way is to create a button event dispatch class that lets other controllers subscribe and unsubscribe to button events. https://en.wikipedia.org/wiki/Publish–subscribe_pattern
